### ISSUE TITLE
Can't mine blocks

### ISSUE THREAD

**Issue by notlesh** [Polkadot-Blockchain-Academy/Academy-PoW#46] opened 2023-07-14 22:26 UTC
When running a node with `--dev`, I cannot mine blocks. Logs:

```
./target/release/academy-pow --dev
2023-07-14 16:23:35 Academy PoW Chain    
2023-07-14 16:23:35 ✌️  version 3.0.0-92bd1ddbf1a    
2023-07-14 16:23:35 ❤️  by Anonymous, 2019-2023    
2023-07-14 16:23:35 📋 Chain specification: Development    
2023-07-14 16:23:35 🏷  Node name: omniscient-hammer-5823    
2023-07-14 16:23:35 👤 Role: AUTHORITY    
2023-07-14 16:23:35 💾 Database: RocksDb at /tmp/substratejU0aEl/chains/dev/db/full    
2023-07-14 16:23:35 ⛓  Native runtime: frontier-template-1 (frontier-template-1.tx1.au1)    
2023-07-14 16:23:35 🔨 Initializing Genesis block/state (state: 0x687d…0e75, header-hash: 0x0b5d…f89b)    
2023-07-14 16:23:35 Using default protocol ID "sup" because none is configured in the chain specs    
2023-07-14 16:23:35 🏷  Local node identity is: 12D3KooWB7Ee5RScT2oiLNYdpcUcGitxNQDdqU7XLtSscCKTE1d9    
2023-07-14 16:23:36 💻 Operating system: linux    
2023-07-14 16:23:36 💻 CPU architecture: x86_64    
2023-07-14 16:23:36 💻 Target environment: gnu    
2023-07-14 16:23:36 💻 CPU: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz    
2023-07-14 16:23:36 💻 CPU cores: 8    
2023-07-14 16:23:36 💻 Memory: 31834MB    
2023-07-14 16:23:36 💻 Kernel: 5.19.0-46-generic    
2023-07-14 16:23:36 💻 Linux distribution: Ubuntu 22.04.2 LTS    
2023-07-14 16:23:36 💻 Virtual machine: no    
2023-07-14 16:23:36 📦 Highest known block at #0    
2023-07-14 16:23:36 〽️ Prometheus exporter started at 127.0.0.1:9615    
2023-07-14 16:23:36 Running JSON-RPC HTTP server: addr=127.0.0.1:9933, allowed origins=["*"]    
2023-07-14 16:23:36 Running JSON-RPC WS server: addr=127.0.0.1:9944, allowed origins=["*"]    
2023-07-14 16:23:36 Accepting new connection 1/100
2023-07-14 16:23:41 💤 Idle (0 peers), best: #0 (0x0b5d…f89b), finalized #0 (0x0b5d…f89b), ⬇ 0 ⬆ 0    
2023-07-14 16:23:46 🙌 Starting consensus session on top of parent 0x0b5d65c66a9b0f8433a905af9a2c1b6120a640e85cd646b62af112d9b4b8f89b    
2023-07-14 16:23:46 💤 Idle (0 peers), best: #0 (0x0b5d…f89b), finalized #0 (0x0b5d…f89b), ⬇ 0 ⬆ 0    
2023-07-14 16:23:46 🎁 Prepared block for proposing at 1 (2 ms) [hash: 0xe88bbd2ee645766f98824950bbcca1b9f0b9044caec8a2b982538da830eab921; parent_hash: 0x0b5d…f89b; extrinsics (2): [0x7f3b…a385, 0x1162…d785]]    
2023-07-14 16:23:47 Unable to import mined block: seal is invalid    
2023-07-14 16:23:48 Unable to import mined block: seal is invalid    
2023-07-14 16:23:48 Unable to import mined block: seal is invalid    
2023-07-14 16:23:49 Unable to import mined block: seal is invalid    
2023-07-14 16:23:49 Unable to import mined block: seal is invalid    
2023-07-14 16:23:49 Unable to import mined block: seal is invalid    
2023-07-14 16:23:50 Unable to import mined block: seal is invalid    
2023-07-14 16:23:50 Unable to import mined block: seal is invalid    
2023-07-14 16:23:51 Unable to import mined block: seal is invalid    
2023-07-14 16:23:51 💤 Idle (0 peers), best: #0 (0x0b5d…f89b), finalized #0 (0x0b5d…f89b), ⬇ 0 ⬆ 0    
2023-07-14 16:23:51 Unable to import mined block: seal is invalid    
2023-07-14 16:23:51 Unable to import mined block: seal is invalid    
2023-07-14 16:23:52 Unable to import mined block: seal is invalid    
2023-07-14 16:23:52 Unable to import mined block: seal is invalid
```

Without `--dev`, I get another hint:

```
💔 Error importing block 0xf398f18ece3c5bb62d6c6325a6c8d9d3b58f325caf9cbf1c611968f4157726f3: consensus error: Import failed: Fetching difficulty from runtime failed: FailedToDecodeReturnValue { function: "DifficultyApi_difficulty", error: Error { cause: Some(Error { cause: None, desc: "Not enough data to fill buffer" }), desc: "Could not decode `Threshold::sha3`" } }
```

**Comment by JoshOrndorff** [comment] 2023-07-18 06:43
> Without --dev, I get another hint

without `--dev`, you are connecting to a bootnode that has a previous version of the PoW consensus. I do need to update the bootnode before running the activity, but this behavior is expected when running without `--dev` for now.

**Comment by JoshOrndorff** [comment] 2023-07-18 06:54
Confirmed this is an issue, and it was caused by #30.

Your options are:
1. find and fix the bug
2. build an older commit
3. use `academy-pow --dev --instant-seal` to skip the pow completely

**Comment by JoshOrndorff** [comment] 2023-07-18 21:20
Ok, so the problem is that I made the node only accept md5 hashes for the first several blocks. This is what I plan to do at the start of the network launch activity. However, I forgot to switch the default mining algorithm, which was still set to sha3.

You can make the current build work by manually by adding the flag `--mining-algo md5`. I'll open a PR to fix this.

**Comment by JoshOrndorff** [comment] 2023-07-18 21:27
Fixed in 92bd1ddbf1a6c894bbcb1b979b6af2c98c0ca1ce

**Closed by JoshOrndorff** 2023-07-18 21:27 UTC
Labels: bug

**Comment by danielbui12** [comment] 2025-01-01 05:48
@JoshOrndorff 

I tried `❯ ./target/release/academy-pow --dev --mining-algo md5 --tmp`, but it seems like stucking at block 20th.

Env:
```
stable-aarch64-apple-darwin
rustc 1.83.0 (90b35a623 2024-11-26)
macos Sequoia
```

<img width="1149" alt="Screenshot 2025-01-01 at 12 46 06" src="https://github.com/user-attachments/assets/6aadbb5c-773a-44ae-85ac-d85562af21d8" />

**Comment by danielbui12** [comment] 2025-01-14 11:57
Due to this function 
```
fn auto_fork_validation(
    parent_number: u32,
    algo: SupportedHashes,
    fork_heights: ForkHeights,
    maxi_position: MaxiPosition,
) -> bool {
    use MaxiPosition::*;
    use SupportedHashes::*;

    if parent_number < fork_heights.add_sha3_keccak {
        // To begin with we only allow md5 hashes for our pow.
        // After the fork height this check is skipped so all the hashes become valid.
        match algo {
            Md5 => true,
            Sha3 => false,
            Keccak => false,
        }
    } else if parent_number < fork_heights.remove_md5 {
        // After the first fork, all three algos become valid.
        match algo {
            Md5 => true,
            Sha3 => true,
            Keccak => true,
        }
    } else if parent_number < fork_heights.split_sha3_keccak {
        // After the second fork, md5 is no longer valid.
        match algo {
            Md5 => false,
            Sha3 => true,
            Keccak => true,
        }
    } else {
        // Finally we have the contentious fork.
        // Our behavior here depends which maxi position we have taken.
        #[allow(clippy::match_like_matches_macro)]
        match (algo, maxi_position) {
            (Sha3, Sha3Maxi) => true,
            (Sha3, NoMaxi) => true,
            (Keccak, KeccakMaxi) => true,
            (Keccak, NoMaxi) => true,
            _ => false,
        }
    }
}
```

and the config of chain spec

<img width="915" alt="Screenshot 2025-01-14 at 18 57 27" src="https://github.com/user-attachments/assets/8116874d-97a4-4954-9de5-1e227010c94a" />



Switch to `manual_mode` then it works fine
